# Generated by Django 3.0.7 on 2020-07-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_restaurants(apps, schema_editor):
    Course = apps.get_model('restaurants', 'Course')
    for course in Course.objects.all():
        course.restaurant = course.restaurant_set.first()
        course.save()


def remove_restaurants(apps, schema_editor):
    Course = apps.get_model('restaurants', 'Course')
    for course in Course.objects.all():
        course.restaurant_set.set([course.restaurant])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0004_auto_20200707_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('delivery_cost', models.PositiveIntegerField(default=0)),
                ('delivery', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='restaurant',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(
                blank=True, related_name='restaurant_set', to='restaurants.Course'),
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='restaurants.Course')),
                ('order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='restaurants.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(
                through='restaurants.OrderEntry', to='restaurants.Course'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(move_restaurants, remove_restaurants),
    ]
